work_folders: !work_folders &work_folders
  data_folder: tests/test_data/work_folder

parla_clarin: !parla_clarin &parla_clarin
  repository_folder: tests/test_data/work_folder/riksdagen-corpus
  repository_url: https://github.com/welfare-state-analytics/riksdagen-corpus.git
  folder: tests/test_data/work_folder/riksdagen-corpus/corpus

extract_speeches: !extract_speeches &extract_speeches
  folder: tests/test_data/work_folder/riksdagen-corpus-export/speech-xml
  template: speeches.cdata.xml
  extension: xml

word_frequency: !word_frequency &word_frequency
  <<: *work_folders
  filename: parla_word_frequencies.pkl

dehyphen: !dehyphen &dehyphen
  <<: *work_folders
  whitelist_filename: dehyphen_whitelist.txt.gz
  whitelist_log_filename: dehyphen_whitelist_log.pkl
  unresolved_filename: dehyphen_unresolved.txt.gz

config: !config
    work_folders: *work_folders
    parla_clarin: *parla_clarin
    extract_speeches: *extract_speeches
    word_frequency: *word_frequency
    dehyphen: *dehyphen
